log:
  level: INFO
  format: common
  filePath: /var/log/traefik/traefik.log

accesslog:
  format: common
  filePath: /var/log/traefik/access.log

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ":443"

  wordpress-db:
    address: ":3306"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "eleazar.sb18@gmail.com"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`inmopage.duckdns.org`)"
      entryPoints:
        - web
        - web-secure
      service: wordpress
      tls:
        certResolver: letsencrypt

  services:
    wordpress:
      loadBalancer:
        servers:
          - url: http://wordpress:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true