log:
  level: INFO

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ':443'

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'eleazar.sb18@gmail.com'
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: 'Host(`developerve.tk`) || Host(`www.developerve.tk`)'
      entryPoints:
        - web
        - web-secure
      middlewares:
        - csrf
      service: nginx_portafolio
      tls:
        certResolver: letsencrypt

    cv_2024_router:
      rule: 'Host(`wordpress.developerve.tk`)'
      entryPoints:
        - web
        - web-secure
      middlewares:
        - csrf
      service: nginx_cv_2024
      tls:
        certResolver: letsencrypt


  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    nginx_portafolio:
      loadBalancer:
        servers:
          - url: http://nginx_portafolio

    nginx_cv_2024:
      loadBalancer:
        servers:
          - url: http://nginx_cv_2024

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
