log:
  level: INFO  # Nivel de registro de información

entryPoints:
  web:
    # http
    address: ':80'
    # http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      # redirections:
      #   entryPoint:
      #     to: web-secure

  web-secure:
    # https
    address: ':443'  


certificatesResolvers:
  letsencrypt:
    acme:
      email: 'eleazar.sb18@gmail.com' 
      storage: /etc/traefik/acme/acme.json 
      httpChallenge:
        entryPoint: web  

http:
  routers:
    web-secure-router:
      rule: 'Host(`inmopage.duckdns.org`)' 
      entryPoints:
        - web  
        - web-secure  
      service: nginx  
      tls:
        certResolver: letsencrypt 

  services:
    nginx:
      loadBalancer:
        servers:
          - url: http://nginx:80
providers:
  file:
    filename: /etc/traefik/traefik.yml  
    watch: true  